# Generated by Django 4.2 on 2025-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('empresa', models.CharField(max_length=30, verbose_name='Empresa')),
                ('cliente', models.CharField(max_length=30, verbose_name='Cliente')),
                ('destino', models.CharField(max_length=30, verbose_name='Destino')),
                ('cant_pallets', models.DecimalField(decimal_places=1, max_digits=3)),
                ('demora', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=30)),
            ],
        ),
    ]
