# Generated by Django 4.2 on 2025-04-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='demora',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Demora'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='empresa',
            field=models.CharField(choices=[('Don Satur', 'Empresa 1'), ('Mani King', 'Empresa 2'), ('Leiva', 'Empresa 3'), ('Hojalmar', 'Empresa 4'), ('Mafalda', 'Empresa 5')], max_length=30, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
