# Generated by Django 4.2 on 2025-04-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ean', models.CharField(max_length=13)),
                ('dun', models.CharField(max_length=14)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('producto', models.CharField(max_length=30, verbose_name='Producto')),
                ('presentacion', models.CharField(max_length=30, verbose_name='Presentacion')),
                ('uxb', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.CharField(max_length=30)),
                ('familia', models.CharField(max_length=30)),
                ('acciones', models.CharField(max_length=30)),
            ],
        ),
    ]
